services:
  backend:
    container_name: blockmen-backend 
    env_file: ".env"
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        BUILD_DATE: "${BUILD_DATE}"
        BUILD_ID: "${BUILD_ID}"
        BRANCH: "${BRANCH}"
    ports:
      - "9090:8000"
    hostname: backend 
    pull_policy: build
    volumes:
      - ./api:/usr/src/ #ignore
    #never shut down the container, always restart
    restart: unless-stopped 
