services:
  backend:
    container_name: blockmen-backend 
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        BUILD_DATE: "${BUILD_DATE}"
        BUILD_ID: "${BUILD_ID}"
        BRANCH: "${BRANCH}"
    ports:
      - "3000:3000"
    hostname: backend 
    volumes:
      - /usr/src/app/venv #ignore 
    #never shut down the container, always restart
    restart: unless-stopped 
