services:
  backend:
    container_name: blockmen-backend 
    env_file: ".env"
    build: 
      context: ./api
      dockerfile: Dockerfile
      args:
        BUILD_DATE: "${BUILD_DATE}"
        BUILD_ID: "${BUILD_ID}"
        BRANCH: "${BRANCH}"
    ports:
      - "9090:8000"
    hostname: backend 
    volumes:
      - ./api/:/usr/src/app #ignore
      - /usr/src/app/venv #ignore 
    #never shut down the container, always restart
    restart: unless-stopped 
