VITE_BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
VITE_BUILD_ID=$(git rev-parse --short HEAD)
VITE_BRANCH=dev

tsc -b && VITE_BRANCH=$VITE_BRANCH VITE_BUILD_ID=$VITE_BUILD_ID VITE_BUILD_DATE=$VITE_BUILD_DATE  vite build
